# mlFlow Registry QA & Prod pipeline 
trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: |
    pip install databricks-cli
    ~/.local/bin/databricks -h
  displayName: 'Install Databricks CLI'

- script: |
    pip install mlflow
    ~/.local/bin/mlflow --help
  displayName: 'Install Databricks CLI'

- script: |
     mlflow run https://github.com/jjaiwant328/mlflow-arg  -b databricks --backend-config cluster-spec.json --experiment-id 1653021744903094
  displayName: 'Run MLflow job'
