# mlFlow Registry QA & Prod pipeline 
trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: |
    pip install databricks-cli
    ~/.local/bin/databricks -h
  displayName: 'Install Databricks CLI'

- script: |
     python mlflow --experiment-id 1653021744903094
  displayName: 'Run MLflow job'
