# mlFlow Registry QA & Prod pipeline 
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true
  displayName: 'Credentials'

- script: |
    pip install databricks-cli
    ~/.local/bin/databricks -h
  displayName: 'Install Databricks CLI'

- script: |
    pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12854/merge
    ~/.local/bin/mlflow --version
  displayName: 'Install mlflow'

- script: |
    export MLFLOW_TRACKING_URI=databricks
    mlflow run https://github.com/jjaiwant328/mlflow-arg  -b databricks --backend-config cluster-spec.json --experiment-id 1653021744903094
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
  displayName: 'Run MLflow job'
