# mlFlow Registry QA & Prod pipeline 
trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: |
    pip install databricks-cli
    ~/.local/bin/databricks -h
  displayName: 'Install Databricks CLI'

- script: Run mlflow
    python -m train_arguments.py
  displayName: 'Run MLflow job'
